extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReport.html
extent.reporter.spark.config=src/test/resources/extent-config.xml

# Add this to ensure screenshots are properly linked in the Spark Report
screenshot.usage=split

screenshot.dir=target/screenshots
screenshot.rel.path=screenshots/

basefolder.name=MyReports/ExtentReports
basefolder.datetimepattern=d-MMM-YY HH-mm-ss

# System Info
systeminfo.os=Windows 11
systeminfo.user=QA Automation Engineer
systeminfo.build=1.0
systeminfo.AppName=Selenium Cucumber Framework